name: giphy_client
description: A Giphy API Client for Dart compatible Web, Flutter, and server-side dart
version: 1.0.0
homepage: https://www.github.com/brianegan/giphy_client
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0
  http: ^0.13.0

dev_dependencies:
  test: ^1.16.0
  mockito: ^5.0.0-nullsafety.7 
  coverage: ^0.15.2
  pedantic: ^1.10.0
  build_runner: ^1.11.1
